/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.airlineReservation;

/**
 *
 * @author ntedd
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Desktop
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        custMenu = new javax.swing.JMenu();
        addCustomer = new javax.swing.JMenuItem();
        SearchCust = new javax.swing.JMenuItem();
        FlightMenu = new javax.swing.JMenu();
        AddFlight = new javax.swing.JMenuItem();
        BookFlight = new javax.swing.JMenuItem();
        TicketMenu = new javax.swing.JMenu();
        getTicket = new javax.swing.JMenuItem();
        AdminMenu = new javax.swing.JMenu();
        AddAdmin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        custMenu.setText("Cutomer");

        addCustomer.setText("Add Customer");
        addCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerActionPerformed(evt);
            }
        });
        custMenu.add(addCustomer);

        SearchCust.setText("Search Customer");
        SearchCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCustActionPerformed(evt);
            }
        });
        custMenu.add(SearchCust);

        jMenuBar1.add(custMenu);

        FlightMenu.setText("Flight");

        AddFlight.setText("Add Flight");
        AddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightActionPerformed(evt);
            }
        });
        FlightMenu.add(AddFlight);

        BookFlight.setText("Book Flight");
        BookFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookFlightActionPerformed(evt);
            }
        });
        FlightMenu.add(BookFlight);

        jMenuBar1.add(FlightMenu);

        TicketMenu.setText("Ticket");

        getTicket.setText("View Ticket");
        getTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTicketActionPerformed(evt);
            }
        });
        TicketMenu.add(getTicket);

        jMenuBar1.add(TicketMenu);

        AdminMenu.setText("Admin");

        AddAdmin.setText("Add Admin");
        AddAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAdminActionPerformed(evt);
            }
        });
        AdminMenu.add(AddAdmin);

        jMenuBar1.add(AdminMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerActionPerformed
        // TODO add your handling code here:
        Add_Customer customer = new Add_Customer();
        Desktop.add(customer);
        customer.setVisible(true);
    }//GEN-LAST:event_addCustomerActionPerformed

    private void AddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightActionPerformed
        // TODO add your handling code here:
        AddFlight flight = new AddFlight();
        Desktop.add(flight);
        flight.setVisible(true);
    }//GEN-LAST:event_AddFlightActionPerformed

    private void AddAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAdminActionPerformed
        // TODO add your handling code here:
        AddAdmin admin = new AddAdmin();
        Desktop.add(admin);
        admin.setVisible(true);
    }//GEN-LAST:event_AddAdminActionPerformed

    private void SearchCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCustActionPerformed
        // TODO add your handling code here:
        SearchCustomer customer = new SearchCustomer();
        Desktop.add(customer);
        customer.setVisible(true);
    }//GEN-LAST:event_SearchCustActionPerformed

    private void BookFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookFlightActionPerformed
        // TODO add your handling code here:
        BookTicket ticket = new BookTicket();
        Desktop.add(ticket);
        ticket.setVisible(true);
    }//GEN-LAST:event_BookFlightActionPerformed

    private void getTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTicketActionPerformed
        // TODO add your handling code here:
        GetTicket ticket = new GetTicket();
        Desktop.add(ticket);
        ticket.setVisible(true);
    }//GEN-LAST:event_getTicketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddAdmin;
    private javax.swing.JMenuItem AddFlight;
    private javax.swing.JMenu AdminMenu;
    private javax.swing.JMenuItem BookFlight;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu FlightMenu;
    private javax.swing.JMenuItem SearchCust;
    private javax.swing.JMenu TicketMenu;
    private javax.swing.JMenuItem addCustomer;
    private javax.swing.JMenu custMenu;
    private javax.swing.JMenuItem getTicket;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
